### ISSUE TITLE
Fix styling

### ISSUE THREAD

**Issue by justweb1** [IftachSadeh/paper-range-slider#2]
Could you fix styling to match PolymerElements/paper-slider by default?

**Comment by IftachSadeh** [comment]
Can you please be more specific about which style option you mean?

As far as I could tell, the default look is the same already. The only difference is for the `--paper-slider-active-color` property of `--paper-slider`. In `--paper-range-slider`, it is mapped to the interval between the two knobs (instead of to the interval between the knob and the beginning, as in `--paper-slider`).

**Comment by justweb1** [comment]
sorry, yes paper-slider uses a container to style size, margins, and padding. when I place paper-range-slider next to paper-slider they are different sizes with different padding and margins.

**Comment by justweb1** [comment]
also, it should default colors to the project colors eg. var (--Primary-Color)

**Comment by IftachSadeh** [comment]
Thanks for the suggestions.
Check out the new version (`v0.1.2`), and let me know you find any remaining styling discrepancies.

Enjoy,
Iftach.

**Comment by justweb1** [comment]
Will do.
